# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "776f5c77004258ad2227d4d94e8292e0"
name = "ds-sections"
handle = "ds-sections-1"
application_url = "https://vbulletin-alfred-medicines-deny.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, read_checkouts, write_checkouts"


[auth]
redirect_urls = ["https://vbulletin-alfred-medicines-deny.trycloudflare.com/auth/callback", "https://vbulletin-alfred-medicines-deny.trycloudflare.com/auth/shopify/callback", "https://vbulletin-alfred-medicines-deny.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
